---
configure_dotfiles: yes

dotfiles_repo: "https://github.com/justinasposiunas/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: yes
dotfiles_files:
  - .gitconfig
  - .zshrc

homebrew_installed_packages:
  - composer
  - exercism
  - git
  - httpie
  - node
  - nvm
  - php
  - sqlite
  - tmux
  - tree
  - wget
  - yarn
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_apps:
  - alfred
  - caffeine
  - docker
  - firefox
  - font-fira-code
  - google-chrome
  - insomnia
  - iterm2
  - notion
  - slack
  - sequel-pro
  - spotify
  - spectacle
  - vagrant
  - visual-studio-code
  - vlc
  - zoomus

mas_installed_apps:
  - { id: 1091189122, name: "Bear (1.6.15)" }
  - { id: 1368722917, name: "Effortless (2.0.24)"}
  - { id: 1176895641, name: "Spark - Email App by Readdle (2.3.10)" }
mas_email: ""
mas_password: ""

composer_packages:
  - name: psy/psysh
    state: present
