---
# setup my macbook just the way I like it

- hosts: mac
 
  vars_files:
    - default.config.yml
 
  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: ohmyzsh
      tags: ['ohmyzsh']

  tasks:
    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']