---
- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: folder_details

- set_fact:
    ohmyzsh_exists: folder_details.stat.exists and folder_details.stat.isdir

- include_tasks: ohmyzsh.yml
  when: ohmyzsh_exists == false